<a href="https://colab.research.google.com/github/GonDss7/exploratory-analysis-steam-python/blob/main/Premier_League_raw_core.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lo primero que hago es llamar a las librer√≠as, que se presenten

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Ahora, voy a ir tabla por tabla, realizando un proceso de limpieza, data mining, ordenarlos, homogeneizarlos, empaquetarlos y dejarlos listos :

In [ ]:
team_stats = pd.read_csv('team_stats.csv')
display(team_stats)

,team,players,age,possession,goals,assists,penalty_kicks,penalty_kick_attempts,yellows,reds,expected_goals,expected_assists,progressive_carries,progressive_passes
0,Arsenal,25,26.6,56.8,65,53,2,2,70,6,57.6,43.2,830,1764
1,Aston Villa,28,27.8,51.0,56,45,3,6,74,3,55.7,41.5,709,1326
2,Bournemouth,29,25.9,48.1,55,39,6,7,97,3,62.4,42.6,732,1438
3,Brentford,28,26.6,47.8,64,43,5,6,61,1,57.6,41.3,579,1318
4,Brighton,32,25.7,52.0,60,40,6,6,77,3,56.5,39.7,798,1478
5,Chelsea,29,24.5,57.3,60,46,4,5,99,2,66.7,51.6,848,1573
6,Crystal Palace,29,27.0,43.1,48,37,3,4,80,4,58.7,44.7,491,1140
7,Everton,26,28.8,41.1,38,26,2,2,78,2,40.6,31.5,474,1027
8,Fulham,26,28.8,52.4,53,44,3,4,80,2,47.8,36.9,773,1524
9,Ipswich Town,32,26.6,40.5,34,25,2,2,91,5,33.6,23.7,488,896
10,Leicester City,31,27.4,45.6,33,25,2,3,85,0,32.4,25.0,569,1068
11,Liverpool,24,28.0,57.4,84,64,9,9,65,2,80.0,59.6,801,1846
12,Manchester City,29,27.6,61.6,69,51,2,3,59,2,65.2,52.5,1112,1890
13,Manchester Utd,31,26.3,53.2,40,28,3,3,84,3,49.7,37.9,669,1379
14,Newcastle Utd,24,28.2,50.9,66,50,5,6,67,1,62.6,45.2,727,1541
15,Nott'ham Forest,23,27.0,40.9,57,42,3,3,88,2,44.3,32.1,610,1079
16,Southampton,36,26.1,48.8,24,15,0,2,89,3,32.0,24.5,628,1114
17,Tottenham,31,25.8,55.2,60,47,2,3,69,1,56.8,43.1,827,1582
18,West Ham,27,29.0,48.2,40,26,3,3,81,3,45.9,33.0,617,1192
19,Wolves,31,27.7,48.1,52,41,0,0,77,2,42.6,34.6,587,1148

In [ ]:
# Drop the last 4 columns
team_stats = team_stats.drop(team_stats.columns[-4:], axis=1)

# Display the updated DataFrame
display(team_stats)

,team,players,age,possession,goals,assists,penalty_kicks,penalty_kick_attempts,yellows,reds
0,Arsenal,25,26.6,56.8,65,53,2,2,70,6
1,Aston Villa,28,27.8,51.0,56,45,3,6,74,3
2,Bournemouth,29,25.9,48.1,55,39,6,7,97,3
3,Brentford,28,26.6,47.8,64,43,5,6,61,1
4,Brighton,32,25.7,52.0,60,40,6,6,77,3
5,Chelsea,29,24.5,57.3,60,46,4,5,99,2
6,Crystal Palace,29,27.0,43.1,48,37,3,4,80,4
7,Everton,26,28.8,41.1,38,26,2,2,78,2
8,Fulham,26,28.8,52.4,53,44,3,4,80,2
9,Ipswich Town,32,26.6,40.5,34,25,2,2,91,5
10,Leicester City,31,27.4,45.6,33,25,2,3,85,0
11,Liverpool,24,28.0,57.4,84,64,9,9,65,2
12,Manchester City,29,27.6,61.6,69,51,2,3,59,2
13,Manchester Utd,31,26.3,53.2,40,28,3,3,84,3
14,Newcastle Utd,24,28.2,50.9,66,50,5,6,67,1
15,Nott'ham Forest,23,27.0,40.9,57,42,3,3,88,2
16,Southampton,36,26.1,48.8,24,15,0,2,89,3
17,Tottenham,31,25.8,55.2,60,47,2,3,69,1
18,West Ham,27,29.0,48.2,40,26,3,3,81,3
19,Wolves,31,27.7,48.1,52,41,0,0,77,2

In [ ]:
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   team                   20 non-null     object
 1   players                20 non-null     int64
 2   age                    20 non-null     float64
 3   possession             20 non-null     float64
 4   goals                  20 non-null     int64
 5   assists                20 non-null     int64
 6   penalty_kicks          20 non-null     int64
 7   penalty_kick_attempts  20 non-null     int64
 8   yellows                20 non-null     int64
 9   reds                   20 non-null     int64
dtypes: float64(2), int64(7), object(1)
memory usage: 1.7+ KB

In [ ]:
# Check for null values in each column
null_values = team_stats.isnull().sum()

# Display the count of null values per column
display(null_values)

team                     0
players                  0
age                      0
possession               0
goals                    0
assists                  0
penalty_kicks            0
penalty_kick_attempts    0
yellows                  0
reds                     0
dtype: int64

In [ ]:
team_salary = pd.read_csv('team_salary.csv')
display(team_salary)

               team  players   weekly     annual
0   Manchester City       61  5211401  270992872
1    Manchester Utd       60  4668844  242779887
2           Chelsea       71  4443518  231062958
3           Arsenal       51  4373711  227432965
4         Liverpool       60  3325255  172913278
5       Aston Villa       68  2776192  144361995
6         Tottenham       66  2705714  140697102
7     Newcastle Utd       62  2666111  138637776
8          West Ham       54  2329155  121116085
9           Everton       54  1843859   95880658
10   Crystal Palace       63  1802243   93716625
11           Fulham       53  1765997   91831819
12   Leicester City       57  1688806   87817887
13  Nott'ham Forest       62  1639135   85235009
14         Brighton       71  1599532   83175683
15      Southampton       68  1446493   75217626
16      Bournemouth       56  1412260   73437533
17           Wolves       70  1374000   71448017
18        Brentford       57  1070606   55671515
19     Ipswich Town       56   883334   45933362

In [ ]:
team_salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   team     20 non-null     object
 1   players  20 non-null     int64
 2   weekly   20 non-null     int64
 3   annual   20 non-null     int64
dtypes: int64(3), object(1)
memory usage: 772.0+ bytes

In [ ]:
# Check for null values in each column
null_values = team_salary.isnull().sum()

# Display the count of null values per column
display(null_values)

team       0
players    0
weekly     0
annual     0
dtype: int64

In [ ]:
team_possession_stats = pd.read_csv('team_possession_stats.csv')
display(team_possession_stats)

,team,possession,touches,deffensive_touches,middle_touches,attacking_touches,attempted_take_ons,successful_take_ons,carries,total_distance_carried
0,Arsenal,56.8,23363,5960,10107,7471,706,310,13816,73408
1,Aston Villa,51.0,21291,7113,9119,5275,706,317,12118,67517
2,Bournemouth,48.1,20971,6300,9029,5902,651,284,11283,66571
3,Brentford,47.8,20864,8064,7830,5166,609,262,11008,60063
4,Brighton,52.0,22986,7355,9983,5913,777,328,13554,74918
5,Chelsea,57.3,24671,7379,11139,6367,769,322,14242,76825
6,Crystal Palace,43.1,19925,7445,8276,4393,479,200,10028,50667
7,Everton,41.1,18989,6745,7761,4689,622,274,9338,49840
8,Fulham,52.4,23328,7797,9590,6184,623,281,13741,72323
9,Ipswich Town,40.5,18531,7601,7286,3850,626,270,9052,51629
10,Leicester City,45.6,21309,7855,9685,3976,627,259,12065,60544
11,Liverpool,57.4,25092,7133,11187,6995,661,295,14444,73791
12,Manchester City,61.6,27459,6350,11762,9571,780,370,17678,101274
13,Manchester Utd,53.2,23978,8418,10137,5646,614,252,14601,72739
14,Newcastle Utd,50.9,22350,7319,9347,5905,644,277,12632,68484
15,Nott'ham Forest,40.9,18416,6288,7448,4910,570,257,8513,48176
16,Southampton,48.8,22284,8220,9579,4682,715,298,12454,65799
17,Tottenham,55.2,23886,7914,10033,6174,798,303,14833,81603
18,West Ham,48.2,22119,8082,9479,4769,776,334,11298,57335
19,Wolves,48.1,21741,7610,9835,4559,704,310,12101,65076

In [ ]:
# Drop the last 7 columns from team_possession_stats
team_possession_stats = team_possession_stats.drop(team_possession_stats.columns[-7:], axis=1)

# Display the updated DataFrame
display(team_possession_stats)

               team  possession  touches
0           Arsenal        56.8    23363
1       Aston Villa        51.0    21291
2       Bournemouth        48.1    20971
3         Brentford        47.8    20864
4          Brighton        52.0    22986
5           Chelsea        57.3    24671
6    Crystal Palace        43.1    19925
7           Everton        41.1    18989
8            Fulham        52.4    23328
9      Ipswich Town        40.5    18531
10   Leicester City        45.6    21309
11        Liverpool        57.4    25092
12  Manchester City        61.6    27459
13   Manchester Utd        53.2    23978
14    Newcastle Utd        50.9    22350
15  Nott'ham Forest        40.9    18416
16      Southampton        48.8    22284
17        Tottenham        55.2    23886
18         West Ham        48.2    22119
19           Wolves        48.1    21741

In [ ]:
# Check for null values in each column
null_values = team_possession_stats.isnull().sum()

# Display the count of null values per column
display(null_values)

team          0
possession    0
touches       0
dtype: int64

In [ ]:
standings = pd.read_csv('standings.csv')
display(standings)

,rank,team,win,loss,draw,goals,conceded,points,last5,top_scorer,keeper
0,1,Liverpool,25,4,8,85,40,83,W W L D L,Mohamed Salah,Alisson
1,2,Arsenal,19,4,14,67,33,71,W D L D W,Kai Havertz,David Raya
2,3,Manchester City,20,9,8,70,44,68,W W W D W,Erling Haaland,Ederson
3,4,Newcastle Utd,20,11,6,68,46,66,L W D W L,Alexander Isak,Nick Pope
4,5,Chelsea,19,9,9,63,43,66,W W W L W,Cole Palmer,Robert S√°nchez
5,6,Aston Villa,19,9,9,58,49,66,W L W W W,Ollie Watkins,Emiliano Mart√≠nez
6,7,Nott'ham Forest,19,10,8,58,45,65,W L D D W,Chris Wood,Matz Sels
7,8,Brighton,15,9,13,62,58,58,L W D W W,"Kaoru Mitoma, Danny Welbeck...",Bart Verbruggen
8,9,Brentford,16,14,7,65,56,55,W W W W L,"Yoane Wissa, Bryan Mbeumo",Mark Flekken
9,10,Fulham,15,13,9,54,52,54,L W L L W,Ra√∫l Jim√©nez,Bernd Leno
10,11,Bournemouth,14,12,11,56,46,53,D D W L L,Justin Kluivert,Kepa Arrizabalaga
11,12,Crystal Palace,13,11,13,50,50,52,D D D W W,Jean-Philippe Mateta,Dean Henderson
12,13,Everton,10,12,15,41,44,45,L L D W W,Iliman Ndiaye,Jordan Pickford
13,14,Wolves,12,20,5,53,68,41,W W L L L,Matheus Cunha,Jos√© S√°
14,15,West Ham,10,17,10,43,61,40,D L D W L,Jarrod Bowen,Alphonse Areola
15,16,Manchester Utd,10,18,9,42,54,39,L D L L L,Bruno Fernandes,Andr√© Onana
16,17,Tottenham,11,21,5,63,61,38,L L D L L,Brennan Johnson,Guglielmo Vicario
17,18,Leicester City,6,24,7,33,78,25,L L W D W,Jamie Vardy,Mads Hermansen
18,19,Ipswich Town,4,23,10,35,79,22,L L D L L,Liam Delap,Arijanet Muric
19,20,Southampton,2,29,6,25,84,12,D L L D L,Paul Onuachu,Aaron Ramsdale

In [ ]:
# Drop the 'last5' column from the standings DataFrame
standings = standings.drop('last5', axis=1)

# Display the updated DataFrame
display(standings)

,rank,team,win,loss,draw,goals,conceded,points,top_scorer,keeper
0,1,Liverpool,25,4,8,85,40,83,Mohamed Salah,Alisson
1,2,Arsenal,19,4,14,67,33,71,Kai Havertz,David Raya
2,3,Manchester City,20,9,8,70,44,68,Erling Haaland,Ederson
3,4,Newcastle Utd,20,11,6,68,46,66,Alexander Isak,Nick Pope
4,5,Chelsea,19,9,9,63,43,66,Cole Palmer,Robert S√°nchez
5,6,Aston Villa,19,9,9,58,49,66,Ollie Watkins,Emiliano Mart√≠nez
6,7,Nott'ham Forest,19,10,8,58,45,65,Chris Wood,Matz Sels
7,8,Brighton,15,9,13,62,58,58,"Kaoru Mitoma, Danny Welbeck...",Bart Verbruggen
8,9,Brentford,16,14,7,65,56,55,"Yoane Wissa, Bryan Mbeumo",Mark Flekken
9,10,Fulham,15,13,9,54,52,54,Ra√∫l Jim√©nez,Bernd Leno
10,11,Bournemouth,14,12,11,56,46,53,Justin Kluivert,Kepa Arrizabalaga
11,12,Crystal Palace,13,11,13,50,50,52,Jean-Philippe Mateta,Dean Henderson
12,13,Everton,10,12,15,41,44,45,Iliman Ndiaye,Jordan Pickford
13,14,Wolves,12,20,5,53,68,41,Matheus Cunha,Jos√© S√°
14,15,West Ham,10,17,10,43,61,40,Jarrod Bowen,Alphonse Areola
15,16,Manchester Utd,10,18,9,42,54,39,Bruno Fernandes,Andr√© Onana
16,17,Tottenham,11,21,5,63,61,38,Brennan Johnson,Guglielmo Vicario
17,18,Leicester City,6,24,7,33,78,25,Jamie Vardy,Mads Hermansen
18,19,Ipswich Town,4,23,10,35,79,22,Liam Delap,Arijanet Muric
19,20,Southampton,2,29,6,25,84,12,Paul Onuachu,Aaron Ramsdale

In [ ]:
standings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        20 non-null     int64
 1   team        20 non-null     object
 2   win         20 non-null     int64
 3   loss        20 non-null     int64
 4   draw        20 non-null     int64
 5   goals       20 non-null     int64
 6   conceded    20 non-null     int64
 7   points      20 non-null     int64
 8   top_scorer  20 non-null     object
 9   keeper      20 non-null     object
dtypes: int64(7), object(3)
memory usage: 1.7+ KB

In [ ]:
player_stats = pd.read_csv('player_stats.csv')
display(player_stats)

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
0,Max Aarons,England,DF,Bournemouth,25.0,2000.0,3,1,86,0,0,0,0,0,0,0.0,1,8,3
1,Joshua Acheampong,England,DF,Chelsea,19.0,2006.0,4,2,170,0,0,0,0,1,0,0.2,0,8,0
2,Tyler Adams,United States,MF,Bournemouth,26.0,1999.0,27,20,1875,0,3,0,0,7,0,1.6,13,71,10
3,Tosin Adarabioyo,England,DF,Chelsea,27.0,1997.0,21,14,1319,1,1,0,0,3,0,0.9,5,39,1
4,Simon Adingra,Cote dIvoire,"FW,MF",Brighton,23.0,2002.0,28,11,1052,2,2,0,0,0,0,2.4,50,18,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,Ashley Young,England,DF,Everton,39.0,1985.0,31,18,1785,1,3,0,0,6,1,0.3,23,89,32
567,Illia Zabarnyi,Ukraine,DF,Bournemouth,22.0,2002.0,35,34,3019,0,0,0,0,4,1,1.1,26,134,4
568,Oleksandr Zinchenko,Ukraine,"DF,MF",Arsenal,28.0,1996.0,14,4,458,0,1,0,0,1,0,0.3,10,37,12
569,Joshua Zirkzee,Netherlands,"FW,MF",Manchester Utd,24.0,2001.0,32,14,1402,3,1,0,0,2,0,4.8,14,44,69
570,Martin √òdegaard,Norway,MF,Arsenal,26.0,1998.0,29,26,2309,2,8,1,1,4,0,4.7,91,255,151

In [ ]:
# Check for null values in each column
null_values = player_stats.isnull().sum()

# Display the count of null values per column
display(null_values)

name                           0
nation                         3
position                       0
team                           0
age                            3
born                           3
played                         0
starts                         0
minutes                        0
goals                          0
assists                        0
penalty_kicks                  0
penalty_kick_attempts          0
yellow                         0
red                            0
expected_goals                 0
progressive_carries            0
progressive_passes             0
received_progressive_passes    0
dtype: int64

In [ ]:
# Find rows where the 'nation' column is null in player_stats
null_nation_rows = player_stats[player_stats['nation'].isnull()]

# Display the rows with null values in 'nation'
display(null_nation_rows)

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
169,Jake Evans,NaN,FW,Leicester City,NaN,NaN,3,0,19,0,0,0,0,0,0,0.0,0,0,1
324,Mateus Mane,NaN,MF,Wolves,NaN,NaN,1,0,2,0,0,0,0,0,0,0.0,0,0,0
356,Jeremy Monga,NaN,"FW,MF",Leicester City,NaN,NaN,6,0,93,0,0,0,0,0,0,0.2,6,3,10

In [ ]:
# Get the number of unique values in the 'position' column
num_unique_positions = player_stats['position'].nunique()

# Display the result
print(f"Hay {num_unique_positions} tipos de posiciones √∫nicas en el DataFrame.")

Hay 10 tipos de posiciones √∫nicas en el DataFrame.

In [ ]:
# Get the unique values in the 'position' column
unique_positions = player_stats['position'].unique()

# Display the unique positions
print("Los tipos de posiciones √∫nicas son:")
for position in unique_positions:
    print(position)

Los tipos de posiciones √∫nicas son:
DF
MF
FW,MF
GK
FW
FW,DF
DF,MF
MF,DF
MF,FW
DF,FW

In [ ]:
# Fill null values in the 'nation' column with 'England' for the identified rows
player_stats.loc[player_stats['nation'].isnull(), 'nation'] = 'England'

# Verify the changes by displaying the rows that previously had nulls in 'nation'
display(player_stats.loc[null_nation_rows.index])

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
169,Jake Evans,England,FW,Leicester City,NaN,NaN,3,0,19,0,0,0,0,0,0,0.0,0,0,1
324,Mateus Mane,England,MF,Wolves,NaN,NaN,1,0,2,0,0,0,0,0,0,0.0,0,0,0
356,Jeremy Monga,England,"FW,MF",Leicester City,NaN,NaN,6,0,93,0,0,0,0,0,0,0.2,6,3,10

In [ ]:
# Find the row for Jeremy Monga
jeremy_monga_row_index = player_stats[player_stats['Name'] == 'Jeremy Monga'].index

# Update the 'born' and 'age' values for Jeremy Monga
player_stats.loc[jeremy_monga_row_index, 'born'] = 2009
player_stats.loc[jeremy_monga_row_index, 'age'] = 15

# Display the updated row for verification
display(player_stats.loc[jeremy_monga_row_index])

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
356,Jeremy Monga,England,"FW,MF",Leicester City,15.0,2009.0,6,0,93,0,0,0,0,0,0,0.2,6,3,10

In [ ]:
# Find the row for Mateus Mane
mateus_mane_row_index = player_stats[player_stats['Name'] == 'Mateus Mane'].index

# Update the 'born' and 'age' values for Mateus Mane
player_stats.loc[mateus_mane_row_index, 'born'] = 2007
player_stats.loc[mateus_mane_row_index, 'age'] = 17

# Display the updated row for verification
display(player_stats.loc[mateus_mane_row_index])

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
324,Mateus Mane,England,MF,Wolves,17.0,2007.0,1,0,2,0,0,0,0,0,0,0.0,0,0,0

In [ ]:
# Find the row for Jake Evans
jake_evans_row_index = player_stats[player_stats['Name'] == 'Jake Evans'].index

# Update the 'born' and 'age' values for Jake Evans
player_stats.loc[jake_evans_row_index, 'born'] = 2008
player_stats.loc[jake_evans_row_index, 'age'] = 17

# Display the updated row for verification
display(player_stats.loc[jake_evans_row_index])

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
169,Jake Evans,England,FW,Leicester City,17.0,2008.0,3,0,19,0,0,0,0,0,0,0.0,0,0,1

In [ ]:
# Check for null values in each column
null_values_after_update = player_stats.isnull().sum()

# Display the count of null values per column
display(null_values_after_update)

name                           0
nation                         0
position                       0
team                           0
age                            0
born                           0
played                         0
starts                         0
minutes                        0
goals                          0
assists                        0
penalty_kicks                  0
penalty_kick_attempts          0
yellow                         0
red                            0
expected_goals                 0
progressive_carries            0
progressive_passes             0
received_progressive_passes    0
dtype: int64

In [ ]:
player_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       571 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          571 non-null    float64
 5   born                         571 non-null    float64
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(3), int64(12), object(4)
memory usage: 84.9+ KB

In [ ]:
# Convert 'age' and 'born' columns to int64
player_stats['age'] = player_stats['age'].astype(int)
player_stats['born'] = player_stats['born'].astype(int)

# Verify the data types
player_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         571 non-null    object
 1   nation                       571 non-null    object
 2   position                     571 non-null    object
 3   team                         571 non-null    object
 4   age                          571 non-null    int64
 5   born                         571 non-null    int64
 6   played                       571 non-null    int64
 7   starts                       571 non-null    int64
 8   minutes                      571 non-null    int64
 9   goals                        571 non-null    int64
 10  assists                      571 non-null    int64
 11  penalty_kicks                571 non-null    int64
 12  penalty_kick_attempts        571 non-null    int64
 13  yellow                       571 non-null    int64
 14  red                          571 non-null    int64
 15  expected_goals               571 non-null    float64
 16  progressive_carries          571 non-null    int64
 17  progressive_passes           571 non-null    int64
 18  received_progressive_passes  571 non-null    int64
dtypes: float64(1), int64(14), object(4)
memory usage: 84.9+ KB

In [ ]:
display(player_stats)

,name,nation,position,team,age,born,played,starts,minutes,goals,assists,penalty_kicks,penalty_kick_attempts,yellow,red,expected_goals,progressive_carries,progressive_passes,received_progressive_passes
0,Max Aarons,England,DF,Bournemouth,25,2000,3,1,86,0,0,0,0,0,0,0.0,1,8,3
1,Joshua Acheampong,England,DF,Chelsea,19,2006,4,2,170,0,0,0,0,1,0,0.2,0,8,0
2,Tyler Adams,United States,MF,Bournemouth,26,1999,27,20,1875,0,3,0,0,7,0,1.6,13,71,10
3,Tosin Adarabioyo,England,DF,Chelsea,27,1997,21,14,1319,1,1,0,0,3,0,0.9,5,39,1
4,Simon Adingra,Cote dIvoire,"FW,MF",Brighton,23,2002,28,11,1052,2,2,0,0,0,0,2.4,50,18,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,Ashley Young,England,DF,Everton,39,1985,31,18,1785,1,3,0,0,6,1,0.3,23,89,32
567,Illia Zabarnyi,Ukraine,DF,Bournemouth,22,2002,35,34,3019,0,0,0,0,4,1,1.1,26,134,4
568,Oleksandr Zinchenko,Ukraine,"DF,MF",Arsenal,28,1996,14,4,458,0,1,0,0,1,0,0.3,10,37,12
569,Joshua Zirkzee,Netherlands,"FW,MF",Manchester Utd,24,2001,32,14,1402,3,1,0,0,2,0,4.8,14,44,69
570,Martin √òdegaard,Norway,MF,Arsenal,26,1998,29,26,2309,2,8,1,1,4,0,4.7,91,255,151

In [ ]:
player_salaries = pd.read_csv('player_salaries.csv')
display(player_salaries)

                Player Nation Position             Team  Age  Weekly    Annual
0      Kevin De Bruyne    BEL    MF,FW  Manchester City   33  488501  25402046
1       Erling Haaland    NOR       FW  Manchester City   24  457970  23814418
2             Casemiro    BRA       MF   Manchester Utd   32  427438  22226790
3        Mohamed Salah    EGY       FW        Liverpool   32  427438  22226790
4      Bruno Fernandes    POR       MF   Manchester Utd   29  366376  19051534
..                 ...    ...      ...              ...  ...     ...       ...
679  Cameron Humphreys    NaN       CM     Ipswich Town   21    1309     68072
680      George Abbott    NaN       DM        Tottenham   19    1007     52356
681      Rico Richards    ENG       AM      Aston Villa   21    1007     52356
682        Kobei Moore    NaN       CF      Aston Villa   20     805     41885
683    Luca Stephenson    NaN       DM        Liverpool   21     537     27923

[684 rows x 7 columns]

In [ ]:
display(player_salaries)

                Player Position             Team  Age  Weekly    Annual
0      Kevin De Bruyne    MF,FW  Manchester City   33  488501  25402046
1       Erling Haaland       FW  Manchester City   24  457970  23814418
2             Casemiro       MF   Manchester Utd   32  427438  22226790
3        Mohamed Salah       FW        Liverpool   32  427438  22226790
4      Bruno Fernandes       MF   Manchester Utd   29  366376  19051534
..                 ...      ...              ...  ...     ...       ...
679  Cameron Humphreys       CM     Ipswich Town   21    1309     68072
680      George Abbott       DM        Tottenham   19    1007     52356
681      Rico Richards       AM      Aston Villa   21    1007     52356
682        Kobei Moore       CF      Aston Villa   20     805     41885
683    Luca Stephenson       DM        Liverpool   21     537     27923

[684 rows x 6 columns]

In [ ]:
player_possession_stats = pd.read_csv('player_possession_stats.csv')
display(player_possession_stats)

,player,nation,position,team,age,90s,touches,deffensive_touches,middle_touches,attacking_touches,attempted_take_ons,successful_take_ons,takeons_tackled,carries,total_distance_carried,received
0,Max Aarons,ENG,DF,Bournemouth,25.0,1.0,73,19,40,15,2,0,1,41,152,40
1,Joshua Acheampong,ENG,DF,Chelsea,19.0,1.9,137,48,81,8,2,1,0,106,709,111
2,Tyler Adams,USA,MF,Bournemouth,26.0,20.8,1279,338,741,214,17,3,10,622,3119,718
3,Tosin Adarabioyo,ENG,DF,Chelsea,27.0,14.7,1255,596,633,27,5,4,0,733,2991,948
4,Simon Adingra,CIV,"FW,MF",Brighton,23.0,11.7,529,66,168,302,49,21,27,356,2460,372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,Ashley Young,ENG,DF,Everton,39.0,19.8,1154,354,507,300,18,5,9,473,2375,602
567,Illia Zabarnyi,UKR,DF,Bournemouth,22.0,33.5,1985,908,1026,73,8,5,2,1221,7951,1246
568,Oleksandr Zinchenko,UKR,"DF,MF",Arsenal,28.0,5.1,413,77,207,130,4,3,0,235,1151,287
569,Joshua Zirkzee,NED,"FW,MF",Manchester Utd,24.0,15.6,587,71,303,219,35,11,24,327,1483,418
570,Martin √É¬òdegaard,NOR,MF,Arsenal,26.0,25.7,1674,125,705,859,58,24,32,1158,7365,1318

In [ ]:
# Drop the specified columns from player_possession_stats
columns_to_drop = ['nation', 'position', 'age', '90s', 'deffensive_touches', 'middle_touches', 'attacking_touches']
player_possession_stats = player_possession_stats.drop(columns=columns_to_drop)

# Display the first few rows of the updated DataFrame
display(player_possession_stats.head())

,player,team,touches,attempted_take_ons,successful_take_ons,takeons_tackled,carries,total_distance_carried,received
0,Max Aarons,Bournemouth,73,2,0,1,41,152,40
1,Joshua Acheampong,Chelsea,137,2,1,0,106,709,111
2,Tyler Adams,Bournemouth,1279,17,3,10,622,3119,718
3,Tosin Adarabioyo,Chelsea,1255,5,4,0,733,2991,948
4,Simon Adingra,Brighton,529,49,21,27,356,2460,372

In [ ]:
# Check for null values in each column
null_values_possession = player_possession_stats.isnull().sum()

# Display the count of null values per column
display(null_values_possession)

player                    0
team                      0
touches                   0
attempted_take_ons        0
successful_take_ons       0
takeons_tackled           0
carries                   0
total_distance_carried    0
received                  0
dtype: int64

In [ ]:
# Save each DataFrame to a CSV file

# Team DataFrames
team_stats.to_csv('team_stats_cleaned.csv', index=False)
team_salary.to_csv('team_salary_cleaned.csv', index=False)
team_possession_stats.to_csv('team_possession_stats_cleaned.csv', index=False)
standings.to_csv('standings_cleaned.csv', index=False)

# Player DataFrames
player_stats.to_csv('player_stats_cleaned.csv', index=False)
player_salaries.to_csv('player_salaries_cleaned.csv', index=False)

print("Todos los DataFrames han sido guardados como archivos CSV en su entorno de Colab.")
print("Puedes descargarlos desde el explorador de archivos (el √≠cono de carpeta a la izquierda).")

Todos los DataFrames han sido guardados como archivos CSV en su entorno de Colab.
Puedes descargarlos desde el explorador de archivos (el √≠cono de carpeta a la izquierda).

In [ ]:
# Save each DataFrame to a CSV file

# Team DataFrames
team_stats.to_csv('team_stats_cleaned.csv', index=False)
team_salary.to_csv('team_salary_cleaned.csv', index=False)
team_possession_stats.to_csv('team_possession_stats_cleaned.csv', index=False)
standings.to_csv('standings_cleaned.csv', index=False)

# Player DataFrames
player_stats.to_csv('player_stats_cleaned.csv', index=False)
player_salaries.to_csv('player_salaries_cleaned.csv', index=False)
player_possession_stats.to_csv('player_possession_stats_cleaned.csv', index=False)

print("Todos los DataFrames han sido guardados como archivos CSV en su entorno de Colab.")
print("Puedes descargarlos desde el explorador de archivos (el √≠cono de carpeta a la izquierda).")

Todos los DataFrames han sido guardados como archivos CSV en su entorno de Colab.
Puedes descargarlos desde el explorador de archivos (el √≠cono de carpeta a la izquierda).